### ISSUE TITLE
how change to  Compose for Desktop, by JetBrains

### ISSUE THREAD

**Issue by CMingTseng** [ShikaSD/compose-server-side#5]
Dear Sir

i try modify this project but fail 

how use normal library  ?

i find JB publish  "Compose for Desktop" <-- modify from android

the example  

https://github.com/JetBrains/compose-jb/tree/master/examples/imageviewer

can run at android / Desktop use normal version library 

THX

**Comment by ShikaSD** [comment]
Hey, sorry for the possible confusion, but this project is expected to be a prototype, exploration of idea, rather than concrete library that you can run in production.
At the moment, there's no way to use Compose as a common core for multiple platforms, and you'd better use something like fritz2 or kweb to implement webpages on Kotlin.
